# Generated by Django 4.0.1 on 2022-04-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_userpost_userimage_postlikereplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercommunication',
            name='comment',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
