# Generated by Django 4.0.1 on 2022-04-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_usercommunication_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='followersreplay',
        ),
    ]
