# Generated by Django 4.0.1 on 2022-04-06 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_delete_usercommunication'),
    ]

    operations = [
        migrations.CreateModel(
            name='postDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('comments', models.CharField(max_length=20, null=True)),
                ('views', models.IntegerField(null=True)),
                ('PostId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='social.userpost')),
                ('parents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment', to='social.postdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
