# Generated by Django 4.0.1 on 2022-04-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_postdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetails',
            name='comments',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
