# Generated by Django 4.0.1 on 2022-04-08 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_alter_postdetails_parents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLikeReplay',
        ),
    ]
