# Generated by Django 4.0.1 on 2022-04-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_user_is_actives_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='userImage',
            field=models.ImageField(default=None, upload_to='image/'),
        ),
    ]
